export const sourceLanguages = [
  {
    code: 'auto',
    label: 'Auto',
    hidden: true,
    icon: '',
    flag: '',
  },
  {
    code: 'ar',
    label: 'Arabic',
    flag: '🇸🇦',
    icon: 'flag:arab-1x1',
  },
  {
    code: 'zh',
    label: 'Chinese',
    flag: '🇨🇳',
    icon: 'flag:cn-1x1',
  },
  {
    code: 'cs',
    label: 'Czech',
    flag: '🇨🇿',
    icon: 'flag:cz-1x1',
  },
  {
    code: 'da',
    label: 'Danish',
    flag: '🇩🇰',
    icon: 'flag:dk-1x1',
  },
  {
    code: 'nl',
    label: 'Dutch',
    flag: '🇳🇱',
    icon: 'flag:nl-1x1',
  },
  {
    code: 'en',
    label: 'English',
    flag: '🇬🇧',
    icon: 'flag:gb-1x1',
  },
  {
    code: 'fi',
    label: 'Finnish',
    flag: '🇫🇮',
    icon: 'flag:fi-1x1',
  },
  {
    code: 'fr',
    label: 'French',
    flag: '🇫🇷',
    icon: 'flag:fr-1x1',
  },
  {
    code: 'de',
    label: 'German',
    flag: '🇩🇪',
    icon: 'flag:de-1x1',
  },
  {
    code: 'el',
    label: 'Greek',
    flag: '🇬🇷',
    icon: 'flag:gr-1x1',
  },
  {
    code: 'he',
    label: 'Hebrew',
    flag: '🇮🇱',
    icon: 'flag:il-1x1',
  },
  {
    code: 'hi',
    label: 'Hindi',
    flag: '🇮🇳',
    icon: 'flag:in-1x1',
  },
  {
    code: 'hu',
    label: 'Hungarian',
    flag: '🇭🇺',
    icon: 'flag:hu-1x1',
  },
  {
    code: 'id',
    label: 'Indonesian',
    flag: '🇮🇩',
    icon: 'flag:id-1x1',
  },
  {
    code: 'it',
    label: 'Italian',
    flag: '🇮🇹',
    icon: 'flag:it-1x1',
  },
  {
    code: 'ja',
    label: 'Japanese',
    flag: '🇯🇵',
    icon: 'flag:jp-1x1',
  },
  {
    code: 'ko',
    label: 'Korean',
    flag: '🇰🇷',
    icon: 'flag:kr-1x1',
  },
  {
    code: 'pl',
    label: 'Polish',
    flag: '🇵🇱',
    icon: 'flag:pl-1x1',
  },
  {
    code: 'pt',
    label: 'Portuguese',
    flag: '🇵🇹',
    icon: 'flag:pt-1x1',
  },
  {
    code: 'ru',
    label: 'Russian',
    flag: '🇷🇺',
    icon: 'flag:ru-1x1',
  },
  {
    code: 'es',
    label: 'Spanish',
    flag: '🇪🇸',
    icon: 'flag:es-1x1',
  },
  {
    code: 'tr',
    label: 'Turkish',
    flag: '🇹🇷',
    icon: 'flag:tr-1x1',
  },
  {
    code: 'uk',
    label: 'Ukrainian',
    flag: '🇺🇦',
    icon: 'flag:ua-1x1',
  },
  {
    code: 'sv',
    label: 'Swedish',
    flag: '🇸🇪',
    icon: 'flag:se-1x1',
  },
  {
    code: 'sk',
    label: 'Slovak',
    flag: '🇸🇰',
    icon: 'flag:sk-1x1',
  },
  {
    code: 'bg',
    label: 'Bulgarian',
    flag: '🇧🇬',
    icon: 'flag:bg-1x1',
  },
  {
    code: 'ro',
    label: 'Romanian',
    flag: '🇷🇴',
    icon: 'flag:ro-1x1',
  },
  {
    code: 'ba',
    label: 'Bashkir',
    hidden: true,
    flag: '🇷🇺',
    icon: 'flag:ru-1x1',
  },
  {
    code: 'eu',
    label: 'Basque',
    hidden: true,
    flag: '🇪🇸',
    icon: 'flag:es-1x1',
  },
  {
    code: 'be',
    label: 'Belarusian',
    hidden: true,
    flag: '🇧🇾',
    icon: 'flag:by-1x1',
  },
  {
    code: 'bn',
    label: 'Bengali',
    hidden: true,
    flag: '🇧🇩',
    icon: 'flag:bd-1x1',
  },
  {
    code: 'ca',
    label: 'Catalan',
    hidden: true,
    flag: '🇪🇸',
    icon: 'flag:es-1x1',
  },
  {
    code: 'hr',
    label: 'Croatian',
    hidden: true,
    flag: '🇭🇷',
    icon: 'flag:hr-1x1',
  },
  {
    code: 'eo',
    label: 'Esperanto',
    hidden: true,
    flag: '🌍',
    icon: '',
  },
  {
    code: 'et',
    label: 'Estonian',
    hidden: true,
    flag: '🇪🇪',
    icon: 'flag:ee-1x1',
  },
  {
    code: 'gl',
    label: 'Galician',
    hidden: true,
    flag: '🇪🇸',
    icon: 'flag:es-1x1',
  },
  {
    code: 'ia',
    label: 'Interlingua',
    hidden: true,
    flag: '🌍',
    icon: '',
  },
  {
    code: 'ga',
    label: 'Irish',
    hidden: true,
    flag: '🇮🇪',
    icon: 'flag:ie-1x1',
  },
  {
    code: 'lv',
    label: 'Latvian',
    hidden: true,
    flag: '🇱🇻',
    icon: 'flag:lv-1x1',
  },
  {
    code: 'lt',
    label: 'Lithuanian',
    hidden: true,
    flag: '🇱🇹',
    icon: 'flag:lt-1x1',
  },
  {
    code: 'ms',
    label: 'Malay',
    hidden: true,
    flag: '🇲🇾',
    icon: 'flag:my-1x1',
  },
  {
    code: 'mt',
    label: 'Maltese',
    hidden: true,
    flag: '🇲🇹',
    icon: 'flag:mt-1x1',
  },
  {
    code: 'mr',
    label: 'Marathi',
    hidden: true,
    flag: '🇮🇳',
    icon: 'flag:in-1x1',
  },
  {
    code: 'mn',
    label: 'Mongolian',
    hidden: true,
    flag: '🇲🇳',
    icon: 'flag:mn-1x1',
  },
  {
    code: 'no',
    label: 'Norwegian',
    hidden: true,
    flag: '🇳🇴',
    icon: 'flag:no-1x1',
  },
  {
    code: 'fa',
    label: 'Persian',
    hidden: true,
    flag: '🇮🇷',
    icon: 'flag:ir-1x1',
  },
  {
    code: 'sl',
    label: 'Slovenian',
    hidden: true,
    flag: '🇸🇮',
    icon: 'flag:si-1x1',
  },
  {
    code: 'sw',
    label: 'Swahili',
    hidden: true,
    flag: '🇹🇿',
    icon: 'flag:tz-1x1',
  },
  {
    code: 'ta',
    label: 'Tamil',
    hidden: true,
    flag: '🇮🇳',
    icon: 'flag:in-1x1',
  },
  {
    code: 'th',
    label: 'Thai',
    hidden: true,
    flag: '🇹🇭',
    icon: 'flag:th-1x1',
  },
  {
    code: 'ur',
    label: 'Urdu',
    hidden: true,
    flag: '🇵🇰',
    icon: 'flag:pk-1x1',
  },
  {
    code: 'ug',
    label: 'Uyghur',
    hidden: true,
    flag: '🇨🇳',
    icon: 'flag:cn-1x1',
  },
  {
    code: 'vi',
    label: 'Vietnamese',
    hidden: true,
    flag: '🇻🇳',
    icon: 'flag:vn-1x1',
  },
  {
    code: 'cy',
    label: 'Welsh',
    hidden: true,
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    icon: 'flag:gb-wls-1x1',
  },
] as const;

export type SourceLangCode = typeof sourceLanguages[number]['code'];