export const targetLanguages = [
  {
    code: 'ar-sa',
    label: 'Arabic (Saudi)',
    short: 'ar',
    flag: '🇸🇦',
    icon: 'flag:sa-1x1',
  },
  {
    code: 'ar-ae',
    label: 'Arabic (UAE)',
    short: 'ar',
    flag: '🇦🇪',
    icon: 'flag:ae-1x1',
  },
  {
    code: 'zh',
    label: 'Chinese (Simplified)',
    flag: '🇨🇳',
    icon: 'flag:cn-1x1',
  },
  {
    code: 'yue',
    label: 'Chinese (Cantonese)',
    flag: '🇨🇳',
    icon: 'flag:cn-1x1',
    hidden: true,
  },
  {
    code: 'zh-hant',
    label: 'Chinese (Traditional)',
    flag: '🇨🇳',
    icon: 'flag:cn-1x1',
  },
  {
    code: 'en-gb',
    label: 'English (British)',
    short: 'en',
    flag: '🇬🇧',
    icon: 'flag:gb-1x1',
    hidden: true,
  },
  {
    code: 'en-us',
    label: 'English',
    short: 'en',
    flag: '🇺🇸',
    icon: 'flag:us-1x1',
  },
  {
    code: 'fr',
    label: 'French',
    flag: '🇫🇷',
    icon: 'flag:fr-1x1',
  },
  {
    code: 'de',
    label: 'German',
    flag: '🇩🇪',
    icon: 'flag:de-1x1',
  },
  {
    code: 'hi',
    label: 'Hindi',
    flag: '🇮🇳',
    icon: 'flag:in-1x1',
  },
  {
    code: 'id',
    label: 'Indonesian',
    flag: '🇮🇩',
    icon: 'flag:id-1x1',
  },
  {
    code: 'it',
    label: 'Italian',
    flag: '🇮🇹',
    icon: 'flag:it-1x1',
  },
  {
    code: 'ja',
    label: 'Japanese',
    flag: '🇯🇵',
    icon: 'flag:jp-1x1',
  },
  {
    code: 'ko',
    label: 'Korean',
    flag: '🇰🇷',
    icon: 'flag:kr-1x1',
  },
  {
    code: 'pt',
    label: 'Portuguese',
    flag: '🇵🇹',
    icon: 'flag:pt-1x1',
  },
  {
    code: 'pt-br',
    label: 'Portuguese (Brazilian)',
    flag: '🇵🇹',
    icon: 'flag:br-1x1',
  },
  {
    code: 'ru',
    label: 'Russian',
    flag: '🇷🇺',
    icon: 'flag:ru-1x1',
  },
  {
    code: 'es',
    label: 'Spanish',
    flag: '🇪🇸',
    icon: 'flag:es-1x1',
  },
  {
    code: 'es-mx',
    label: 'Spanish (Mexican)',
    flag: '🇲🇽',
    icon: 'flag:mx-1x1',
  },
  {
    code: 'tr',
    label: 'Turkish',
    flag: '🇹🇷',
    icon: 'flag:tr-1x1',
  },
  {
    code: 'uk',
    label: 'Ukrainian',
    flag: '🇺🇦',
    icon: 'flag:ua-1x1',
  },
  {
    code: 'sv',
    label: 'Swedish',
    flag: '🇸🇪',
    icon: 'flag:se-1x1',
  },
  {
    code: 'pl',
    label: 'Polish',
    flag: '🇵🇱',
    icon: 'flag:pl-1x1',
  },
  {
    code: 'nl',
    label: 'Dutch',
    flag: '🇳🇱',
    icon: 'flag:nl-1x1',
  },
  {
    code: 'fi',
    label: 'Finnish',
    flag: '🇫🇮',
    icon: 'flag:fi-1x1',
  },
  {
    code: 'hu',
    label: 'Hungarian',
    flag: '🇭🇺',
    icon: 'flag:hu-1x1',
  },
  {
    code: 'el',
    label: 'Greek',
    flag: '🇬🇷',
    icon: 'flag:gr-1x1',
  },
  {
    code: 'cs',
    label: 'Czech',
    flag: '🇨🇿',
    icon: 'flag:cz-1x1',
  },
  {
    code: 'da',
    label: 'Danish',
    flag: '🇩🇰',
    icon: 'flag:dk-1x1',
  },
  {
    code: 'en-zh',
    label: 'Chinese English (Experimental)',
    hidden: true,
    flag: '',
    icon: 'flag:cn-1x1',
  },
  {
    code: 'en-gpt',
    label: 'English GPT (Experimental)',
    hidden: true,
    flag: '',
    icon: 'flag:gb-1x1',
  },
  {
    code: 'en-palabra-llm',
    label: 'English Palabra LLM (Experimental)',
    hidden: true,
    flag: '',
    icon: 'flag:us-1x1',
  },
  {
    code: 'en-orpheus',
    label: 'English-o',
    hidden: true,
    flag: '',
    icon: 'flag:us-1x1',
  },
  {
    code: 'fr-orpheus',
    label: 'French-o',
    hidden: true,
    flag: '',
    icon: 'flag:fr-1x1',
  },
  {
    code: 'de-orpheus',
    label: 'German-o',
    hidden: true,
    flag: '',
    icon: 'flag:de-1x1',
  },
  {
    code: 'ko-orpheus',
    label: 'Korean-o',
    hidden: true,
    flag: '',
    icon: 'flag:kr-1x1',
  },
  {
    code: 'zh-orpheus',
    label: 'Chinese-o',
    hidden: true,
    flag: '',
    icon: 'flag:cn-1x1',
  },
  {
    code: 'bg',
    label: 'Bulgarian',
    flag: '🇧🇬',
    icon: 'flag:bg-1x1',
  },
  {
    code: 'ro',
    label: 'Romanian',
    flag: '🇷🇴',
    icon: 'flag:ro-1x1',
  },
  {
    code: 'sk',
    label: 'Slovak',
    flag: '🇸🇰',
    icon: 'flag:sk-1x1',
  },

  {
    code: 'en-au',
    label: 'English (Australian)',
    hidden: true,
    short: 'en',
    flag: '🇦🇺',
    icon: 'flag:au-1x1',
  },
  {
    code: 'en-ca',
    label: 'English (Canadian)',
    hidden: true,
    short: 'en',
    flag: '🇨🇦',
    icon: 'flag:ca-1x1',
  },
  {
    code: 'fr-ca',
    label: 'French (Canadian)',
    hidden: true,
    short: 'fr',
    flag: '🇨🇦',
    icon: 'flag:ca-1x1',
  },
  {
    code: 'fil',
    label: 'Filipino',
    hidden: true,
    flag: '🇵🇭',
    icon: 'flag:ph-1x1',
  },
  {
    code: 'hr',
    label: 'Croatian',
    hidden: true,
    flag: '🇭🇷',
    icon: 'flag:hr-1x1',
  },
  {
    code: 'ms',
    label: 'Malay',
    hidden: true,
    flag: '🇲🇾',
    icon: 'flag:my-1x1',
  },
  {
    code: 'ta',
    label: 'Tamil',
    hidden: true,
    flag: '🇮🇳',
    icon: 'flag:in-1x1',
  },
] as const;

export type TargetLangCode = typeof targetLanguages[number]['code'];